# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SalaryCalcDesign.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTimeEdit, QWidget)

class Ui_SalaryCalculator(object):
    def setupUi(self, SalaryCalculator):
        if not SalaryCalculator.objectName():
            SalaryCalculator.setObjectName(u"SalaryCalculator")
        SalaryCalculator.resize(813, 985)
        font = QFont()
        font.setPointSize(13)
        SalaryCalculator.setFont(font)
        SalaryCalculator.setAutoFillBackground(True)
        self.centralwidget = QWidget(SalaryCalculator)
        self.centralwidget.setObjectName(u"centralwidget")
        self.calendarWidget = QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(230, 40, 304, 173))
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setAutoFillBackground(False)
        self.ClearButton = QPushButton(self.centralwidget)
        self.ClearButton.setObjectName(u"ClearButton")
        self.ClearButton.setGeometry(QRect(330, 210, 91, 31))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        self.ClearButton.setFont(font1)
        self.ClearButton.setCheckable(False)
        self.ClearButton.setChecked(False)
        self.StartTime = QTimeEdit(self.centralwidget)
        self.StartTime.setObjectName(u"StartTime")
        self.StartTime.setGeometry(QRect(280, 290, 81, 22))
        self.EndTime = QTimeEdit(self.centralwidget)
        self.EndTime.setObjectName(u"EndTime")
        self.EndTime.setGeometry(QRect(410, 290, 81, 22))
        self.HrsWorkedLabel = QLabel(self.centralwidget)
        self.HrsWorkedLabel.setObjectName(u"HrsWorkedLabel")
        self.HrsWorkedLabel.setGeometry(QRect(290, 270, 201, 20))
        self.HrsWorkedLabel.setAlignment(Qt.AlignCenter)
        self.HrsWorkedLabel.setWordWrap(True)
        self.AddHours = QPushButton(self.centralwidget)
        self.AddHours.setObjectName(u"AddHours")
        self.AddHours.setGeometry(QRect(500, 280, 41, 41))
        self.Start_2 = QLabel(self.centralwidget)
        self.Start_2.setObjectName(u"Start_2")
        self.Start_2.setGeometry(QRect(240, 290, 31, 16))
        self.End_2 = QLabel(self.centralwidget)
        self.End_2.setObjectName(u"End_2")
        self.End_2.setGeometry(QRect(380, 290, 31, 16))
        self.SalaryInput = QLineEdit(self.centralwidget)
        self.SalaryInput.setObjectName(u"SalaryInput")
        self.SalaryInput.setGeometry(QRect(380, 240, 71, 21))
        self.HourlyPay = QLabel(self.centralwidget)
        self.HourlyPay.setObjectName(u"HourlyPay")
        self.HourlyPay.setGeometry(QRect(310, 240, 71, 16))
        self.HOW = QLabel(self.centralwidget)
        self.HOW.setObjectName(u"HOW")
        self.HOW.setGeometry(QRect(230, 330, 311, 16))
        font2 = QFont()
        font2.setFamilies([u"Soloist Extra-Italic"])
        font2.setPointSize(13)
        font2.setBold(True)
        font2.setItalic(True)
        font2.setUnderline(True)
        self.HOW.setFont(font2)
        self.HOW.setAcceptDrops(False)
        self.HOW.setTextFormat(Qt.RichText)
        self.ExtraPay_1_label_2 = QLabel(self.centralwidget)
        self.ExtraPay_1_label_2.setObjectName(u"ExtraPay_1_label_2")
        self.ExtraPay_1_label_2.setGeometry(QRect(230, 390, 58, 16))
        self.ExtraPay_3_label_2 = QLabel(self.centralwidget)
        self.ExtraPay_3_label_2.setObjectName(u"ExtraPay_3_label_2")
        self.ExtraPay_3_label_2.setGeometry(QRect(230, 430, 58, 16))
        self.ExtraPay_2_label_2 = QLabel(self.centralwidget)
        self.ExtraPay_2_label_2.setObjectName(u"ExtraPay_2_label_2")
        self.ExtraPay_2_label_2.setGeometry(QRect(230, 410, 58, 16))
        self.ExtraPay_1 = QLineEdit(self.centralwidget)
        self.ExtraPay_1.setObjectName(u"ExtraPay_1")
        self.ExtraPay_1.setGeometry(QRect(300, 390, 71, 21))
        self.ExtraPay_2 = QLineEdit(self.centralwidget)
        self.ExtraPay_2.setObjectName(u"ExtraPay_2")
        self.ExtraPay_2.setGeometry(QRect(300, 410, 71, 21))
        self.ExtraPay_3 = QLineEdit(self.centralwidget)
        self.ExtraPay_3.setObjectName(u"ExtraPay_3")
        self.ExtraPay_3.setGeometry(QRect(300, 430, 71, 21))
        self.ExtraPay_1_note = QLineEdit(self.centralwidget)
        self.ExtraPay_1_note.setObjectName(u"ExtraPay_1_note")
        self.ExtraPay_1_note.setGeometry(QRect(380, 390, 141, 21))
        self.ExtraPay_2_note = QLineEdit(self.centralwidget)
        self.ExtraPay_2_note.setObjectName(u"ExtraPay_2_note")
        self.ExtraPay_2_note.setGeometry(QRect(380, 410, 141, 21))
        self.ExtraPay_3_note = QLineEdit(self.centralwidget)
        self.ExtraPay_3_note.setObjectName(u"ExtraPay_3_note")
        self.ExtraPay_3_note.setGeometry(QRect(380, 430, 141, 21))
        self.ExtraPayLabels = QLabel(self.centralwidget)
        self.ExtraPayLabels.setObjectName(u"ExtraPayLabels")
        self.ExtraPayLabels.setGeometry(QRect(400, 370, 91, 16))
        self.ExtraPayLabels.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(530, 420, 21, 32))
        self.HealthLabel = QLabel(self.centralwidget)
        self.HealthLabel.setObjectName(u"HealthLabel")
        self.HealthLabel.setGeometry(QRect(230, 510, 71, 16))
        self.LaborLabel = QLabel(self.centralwidget)
        self.LaborLabel.setObjectName(u"LaborLabel")
        self.LaborLabel.setGeometry(QRect(230, 530, 71, 16))
        self.TaxLabel = QLabel(self.centralwidget)
        self.TaxLabel.setObjectName(u"TaxLabel")
        self.TaxLabel.setGeometry(QRect(230, 550, 71, 16))
        self.HealthInsurCalc = QLineEdit(self.centralwidget)
        self.HealthInsurCalc.setObjectName(u"HealthInsurCalc")
        self.HealthInsurCalc.setGeometry(QRect(300, 510, 71, 21))
        self.LaborInsurCalc = QLineEdit(self.centralwidget)
        self.LaborInsurCalc.setObjectName(u"LaborInsurCalc")
        self.LaborInsurCalc.setGeometry(QRect(300, 530, 71, 21))
        self.TaxRateInput = QLineEdit(self.centralwidget)
        self.TaxRateInput.setObjectName(u"TaxRateInput")
        self.TaxRateInput.setGeometry(QRect(300, 550, 71, 21))
        self.TaxRateInput.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.percent = QLabel(self.centralwidget)
        self.percent.setObjectName(u"percent")
        self.percent.setGeometry(QRect(380, 550, 16, 16))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(330, 580, 100, 32))
        self.TypeToOverride = QLabel(self.centralwidget)
        self.TypeToOverride.setObjectName(u"TypeToOverride")
        self.TypeToOverride.setGeometry(QRect(380, 510, 181, 31))
        self.TypeToOverride.setWordWrap(True)
        self.TotalHoursLabel = QLabel(self.centralwidget)
        self.TotalHoursLabel.setObjectName(u"TotalHoursLabel")
        self.TotalHoursLabel.setGeometry(QRect(230, 350, 121, 16))
        self.SalaryOutput = QLineEdit(self.centralwidget)
        self.SalaryOutput.setObjectName(u"SalaryOutput")
        self.SalaryOutput.setGeometry(QRect(430, 350, 51, 21))
        self.equals = QLabel(self.centralwidget)
        self.equals.setObjectName(u"equals")
        self.equals.setGeometry(QRect(410, 350, 16, 16))
        self.TotalHoursWorked = QLineEdit(self.centralwidget)
        self.TotalHoursWorked.setObjectName(u"TotalHoursWorked")
        self.TotalHoursWorked.setGeometry(QRect(350, 350, 51, 21))
        self.GrossPayLabel = QLabel(self.centralwidget)
        self.GrossPayLabel.setObjectName(u"GrossPayLabel")
        self.GrossPayLabel.setGeometry(QRect(230, 470, 61, 16))
        self.GrossPayOutput = QLineEdit(self.centralwidget)
        self.GrossPayOutput.setObjectName(u"GrossPayOutput")
        self.GrossPayOutput.setGeometry(QRect(300, 470, 71, 21))
        self.YourWage = QLabel(self.centralwidget)
        self.YourWage.setObjectName(u"YourWage")
        self.YourWage.setGeometry(QRect(230, 650, 71, 16))
        self.Wage2 = QLineEdit(self.centralwidget)
        self.Wage2.setObjectName(u"Wage2")
        self.Wage2.setGeometry(QRect(300, 650, 51, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(360, 650, 71, 16))
        self.TotalHoursWorked2 = QLineEdit(self.centralwidget)
        self.TotalHoursWorked2.setObjectName(u"TotalHoursWorked2")
        self.TotalHoursWorked2.setGeometry(QRect(440, 650, 51, 21))
        self.BaseSalary = QLabel(self.centralwidget)
        self.BaseSalary.setObjectName(u"BaseSalary")
        self.BaseSalary.setGeometry(QRect(230, 670, 81, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 770, 81, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 710, 58, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 730, 58, 16))
        self.BaseSalaryOutput = QLineEdit(self.centralwidget)
        self.BaseSalaryOutput.setObjectName(u"BaseSalaryOutput")
        self.BaseSalaryOutput.setGeometry(QRect(310, 670, 141, 21))
        self.BaseSalaryOutput_2 = QLineEdit(self.centralwidget)
        self.BaseSalaryOutput_2.setObjectName(u"BaseSalaryOutput_2")
        self.BaseSalaryOutput_2.setGeometry(QRect(290, 710, 141, 21))
        self.BaseSalaryOutput_3 = QLineEdit(self.centralwidget)
        self.BaseSalaryOutput_3.setObjectName(u"BaseSalaryOutput_3")
        self.BaseSalaryOutput_3.setGeometry(QRect(290, 730, 141, 21))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 800, 58, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(230, 820, 51, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 840, 31, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(230, 860, 71, 16))
        self.PrintButton = QPushButton(self.centralwidget)
        self.PrintButton.setObjectName(u"PrintButton")
        self.PrintButton.setGeometry(QRect(320, 880, 91, 31))
        self.PrintButton.setFont(font1)
        self.PrintButton.setCheckable(False)
        self.PrintButton.setChecked(False)
        SalaryCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(SalaryCalculator)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 813, 24))
        SalaryCalculator.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(SalaryCalculator)
        self.statusbar.setObjectName(u"statusbar")
        SalaryCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(SalaryCalculator)

        QMetaObject.connectSlotsByName(SalaryCalculator)
    # setupUi

    def retranslateUi(self, SalaryCalculator):
        SalaryCalculator.setWindowTitle(QCoreApplication.translate("SalaryCalculator", u"MainWindow", None))
        self.ClearButton.setText(QCoreApplication.translate("SalaryCalculator", u"Clear", None))
        self.HrsWorkedLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Hours worked for Selected Days", None))
        self.AddHours.setText(QCoreApplication.translate("SalaryCalculator", u"Add", None))
        self.Start_2.setText(QCoreApplication.translate("SalaryCalculator", u"Start", None))
        self.End_2.setText(QCoreApplication.translate("SalaryCalculator", u"End", None))
        self.HourlyPay.setText(QCoreApplication.translate("SalaryCalculator", u"Hourly Pay", None))
        self.HOW.setText(QCoreApplication.translate("SalaryCalculator", u"**HERE SHOW DATES & HOURS SELECTED??**", None))
        self.ExtraPay_1_label_2.setText(QCoreApplication.translate("SalaryCalculator", u"Extra Pay", None))
        self.ExtraPay_3_label_2.setText(QCoreApplication.translate("SalaryCalculator", u"Extra Pay", None))
        self.ExtraPay_2_label_2.setText(QCoreApplication.translate("SalaryCalculator", u"Extra Pay", None))
        self.ExtraPay_1_note.setText(QCoreApplication.translate("SalaryCalculator", u"e.g. Assessments", None))
        self.ExtraPayLabels.setText(QCoreApplication.translate("SalaryCalculator", u"Label for Pay", None))
        self.pushButton.setText(QCoreApplication.translate("SalaryCalculator", u"+", None))
        self.HealthLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Health Ins.:", None))
        self.LaborLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Labor Ins.:", None))
        self.TaxLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Tax Rate:", None))
        self.HealthInsurCalc.setText(QCoreApplication.translate("SalaryCalculator", u"710", None))
        self.LaborInsurCalc.setText(QCoreApplication.translate("SalaryCalculator", u"1008", None))
        self.TaxRateInput.setText(QCoreApplication.translate("SalaryCalculator", u"5", None))
        self.percent.setText(QCoreApplication.translate("SalaryCalculator", u"%", None))
        self.pushButton_2.setText(QCoreApplication.translate("SalaryCalculator", u"Calculate", None))
        self.TypeToOverride.setText(QCoreApplication.translate("SalaryCalculator", u"(Type to override calculated rate)", None))
        self.TotalHoursLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Total Hrs Worked at", None))
        self.equals.setText(QCoreApplication.translate("SalaryCalculator", u"=", None))
        self.GrossPayLabel.setText(QCoreApplication.translate("SalaryCalculator", u"Gross Pay", None))
        self.YourWage.setText(QCoreApplication.translate("SalaryCalculator", u"Your Wage:", None))
        self.label.setText(QCoreApplication.translate("SalaryCalculator", u"Total Hours:", None))
        self.BaseSalary.setText(QCoreApplication.translate("SalaryCalculator", u"Base Salary:", None))
        self.label_2.setText(QCoreApplication.translate("SalaryCalculator", u"Gross Salary:", None))
        self.label_3.setText(QCoreApplication.translate("SalaryCalculator", u"Pay for:", None))
        self.label_4.setText(QCoreApplication.translate("SalaryCalculator", u"Pay for:", None))
        self.BaseSalaryOutput_2.setText(QCoreApplication.translate("SalaryCalculator", u"e.g. Assessments", None))
        self.label_5.setText(QCoreApplication.translate("SalaryCalculator", u"Health:", None))
        self.label_6.setText(QCoreApplication.translate("SalaryCalculator", u"Labor:", None))
        self.label_7.setText(QCoreApplication.translate("SalaryCalculator", u"Tax:", None))
        self.label_8.setText(QCoreApplication.translate("SalaryCalculator", u"Net Salary:", None))
        self.PrintButton.setText(QCoreApplication.translate("SalaryCalculator", u"Print", None))
    # retranslateUi

